### ISSUE TITLE
nifty:authentication --help logged_in? error

### ISSUE THREAD

**Issue by carusso** [ryanb/nifty-generators#151]
Just created a new rvm install of ruby-1.9.3-p194 with only the Rails 3.2.3 gems and nifty-generator (and whatever dependencies came in for those things after I did a bundle install)

Issued a "rails g nifty:authentication --help" and the following output appeared:

Usage:
  rails generate nifty:authentication [user_name] [sessions_controller_name] [options]

Options:
  [--haml]       # Generate HAML views instead of ERB.
  [--authlogic]  # Use Authlogic for authentication.

Runtime options:
  -f, [--force]    # Overwrite files that already exist
  -p, [--pretend]  # Run but do not make any changes
  -q, [--quiet]    # Supress status output
  -s, [--skip]     # Skip files that already exist

Test framework options:
  [--testunit]  # Use test/unit for test files.
  [--rspec]     # Use RSpec for test files.
  [--shoulda]   # Use shoulda for test files.

(erb):37:in `desc': undefined method`logged_in?' for Nifty::Generators::AuthenticationGenerator:Class (NoMethodError)
    from /Users/crusso/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/erb.rb:838:in `eval'
    from /Users/crusso/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/erb.rb:838:in`result'
    from /Users/crusso/.rvm/gems/ruby-1.9.3-p194@rentals/gems/railties-3.2.3/lib/rails/generators/base.rb:37:in `desc'
    from /Users/crusso/.rvm/gems/ruby-1.9.3-p194@rentals/gems/thor-0.14.6/lib/thor/group.rb:35:in`help'
    from /Users/crusso/.rvm/gems/ruby-1.9.3-p194@rentals/gems/thor-0.14.6/lib/thor/group.rb:216:in `dispatch'
    from /Users/crusso/.rvm/gems/ruby-1.9.3-p194@rentals/gems/thor-0.14.6/lib/thor/base.rb:389:in`start'
    from /Users/crusso/.rvm/gems/ruby-1.9.3-p194@rentals/gems/railties-3.2.3/lib/rails/generators.rb:170:in `invoke'
    from /Users/crusso/.rvm/gems/ruby-1.9.3-p194@rentals/gems/railties-3.2.3/lib/rails/commands/generate.rb:12:in`<top (required)>'
    from /Users/crusso/.rvm/gems/ruby-1.9.3-p194@rentals/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in `require'
    from /Users/crusso/.rvm/gems/ruby-1.9.3-p194@rentals/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in`block in require'
    from /Users/crusso/.rvm/gems/ruby-1.9.3-p194@rentals/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /Users/crusso/.rvm/gems/ruby-1.9.3-p194@rentals/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in`require'
    from /Users/crusso/.rvm/gems/ruby-1.9.3-p194@rentals/gems/railties-3.2.3/lib/rails/commands.rb:29:in `<top (required)>'
    from script/rails:6:in`require'
    from script/rails:6:in `<main>'

**Comment by detuvoldo** [comment]
great!

**Comment by WolfieWhite** [comment]
Sorry, when I add the extra %% it shows up with the text   "<% if logged_in? %>
    Welcome <%= current_user.username %>! Not you?" in the view on the server site (localhost:3000).
